import type { Picture } from '@sveltejs/enhanced-img';

// Build-time optimized variants (AVIF/WebP/JPEG srcsets + intrinsic sizes) for
// every gallery photo, generated by @sveltejs/enhanced-img. Kept out of
// gallery-data.ts so data-only consumers (unit tests) never pull the image
// pipeline into their module graph.
const modules = import.meta.glob<{ default: Picture }>('./assets/gallery/*.jpg', {
	eager: true,
	query: { enhanced: true }
});

/** Resolve a gallery photo's optimized sources by its asset file name. */
export function galleryImage(file: string): Picture {
	const module = modules[`./assets/gallery/${file}`];

	if (!module) {
		throw new Error(`Unknown gallery image: ${file}`);
	}

	return module.default;
}
