import type { Picture } from '@sveltejs/enhanced-img';

// Build-time optimized variants (AVIF/WebP/JPEG srcsets + intrinsic sizes) for
// every gallery photo, generated by @sveltejs/enhanced-img. Kept out of
// gallery-data.ts so data-only consumers (unit tests) never pull the image
// pipeline into their module graph.
// The `w` widths give the browser real width-based variants to match the
// carousel's `sizes` hint (max slide width is min(86vw, ratio × 640px), so
// ~400w mobile/1x up to ~1280w desktop/2x). Without them enhanced-img only
// emits intrinsic-size 1x/2x density variants, which ignore the rendered
// slot size. Widths above a photo's intrinsic width are skipped, not
// upscaled, so the set is safe for the smaller sources too.
const modules = import.meta.glob<{ default: Picture }>('./assets/gallery/*.jpg', {
	eager: true,
	query: { enhanced: true, w: '400;640;960;1280' }
});

/** Resolve a gallery photo's optimized sources by its asset file name. */
export function galleryImage(file: string): Picture {
	const module = modules[`./assets/gallery/${file}`];

	if (!module) {
		throw new Error(`Unknown gallery image: ${file}`);
	}

	return module.default;
}
