apiVersion: v1
kind: Secret
metadata:
    name: wedding-app-admin-code
    namespace: wedding-app
type: Opaque
stringData:
    ADMIN_CODE: ENC[AES256_GCM,data:KpfpbGSvWgt39j8Rt4UeQSHxEYytFnQ3EQ==,iv:cpuqJG6OKZBWFmjrMDcqdAWnD69GBK4u068wjVXDBdk=,tag:YscnF0Z6NhTxGudEzk7QMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTkkzTUdPUlhlN0s1QXhS
            RnZkOFZkZGJobXVONWtEbFhmMUJNNFNMWlN3CklyU2g5OXNORWI2Um5pT0k2K1Zp
            YkxGdUhTS3lVWjk0TXN3Q3RQaXUxdGMKLS0tIElpNzR3Q1drek1HZzdsd3hhSmN5
            d2JIZEtSQmZ6MGdCZ2duZk5UM1lXcW8KymwFeVgxORpnmNts5yNpH4/tnqiWBmC1
            MjhQaALrv7GXEVNBmYTsMgbwcsBAY68WdjZtEjayVBOjb3fxG0W88Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vce0tzr7c5xzejpkd40s48ux833e3u5hf667xz4g3skes7zxn9gstkusn4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T16:23:18Z"
    mac: ENC[AES256_GCM,data:Fhefb25AJZFIA601rDkui/BC5KhJNOYvVpuno6Teq9v+JSGwD9jxgIDN4Regvayre+6qptb0P/qXhXzfpvMFWEmPavxwca9fuzO4YXM8uDRBpgcz8xtDCeCisyPbiZjz1CFYBP1aPn47VJ9kP4jOjsYTlBDRYU7nYDQwinO+uio=,iv:3Ooak7ZF2jE62wZ3DasYExW8dkFPKZ82Zk8FbLI+S+o=,tag:ioxOngEoIOv/ybflpr4wYQ==,type:str]
    version: 3.13.0
