apiVersion: v1
kind: Secret
metadata:
    name: wedding-db-credentials
    labels:
        app.kubernetes.io/name: wedding-db
        app.kubernetes.io/part-of: wedding-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dKykpn5ZMg==,iv:oNJiiWUQu0BkWwyQrwNAbjgnuDyBEv8uHxwoWYwoq60=,tag:IAN/OFBlAW8AIIAQf4ppUQ==,type:str]
    password: ENC[AES256_GCM,data:aLWIfo8tJsnbrgDvLHYv7YleQ+PYt+fkyCZBqAqeIKM=,iv:zaD6Su/voaGqY3tPaXDLWB2t5L0vTHe40J4GbAhHjIg=,tag:2keP+i52DvSrIyYhaPAbtg==,type:str]
sops:
    age:
        - recipient: age1jq2gy8h7c3y7flnc382u0qmtvgjn8u6pm2jahytgjak7gzvc55qqy0t87y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcnpSRmVUR0x6aHhWaElh
            bHNFbXVaZXlSYXN5TEdMbGU5R2duZ0o3OUVBCk5URkNrMHUwUzVESFF6eGFyQ3Rx
            QUh1dHZRaERjZS9JazVTT25LWHNNZTgKLS0tIGNuYVVWWEFDWHV4a1U1akQvQVd5
            UkNGM1lTV2h2U0Q2aG9UL05QSjNsT3cKUwbm/JkySfiI/W7+/SBmRukZvukXH/A8
            eK9SgHFPeTZOf0u4AA07iJlPON1AjuPi3tLwZ8hCuLiissPpjWucog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T19:37:24Z"
    mac: ENC[AES256_GCM,data:UguOwvNkVU3Jun8XvlII7elH3QRy6CNKlLN1FnwaW/S2xmsV0MCniZMxGM2jveMJ7IN+vw5Mw9XzmcvkMujSapTfnbwhO5uK/H1MmRYDt+ucSYnLD9krNwbsBCNsn1Tc3HOm6gaKN/1JXTksgGydzGsClL/44EgKp0/Ow+aIkVw=,iv:a7R93sQQyhLIg/FSARlxJxKhBka6cDm9FMTwOinZSbE=,tag:kqBk0WNxu+zoVt0bfRQPNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
