name: 🚀 CD
on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  publish:
    name: Publish
    permissions:
      contents: read # checkout
      packages: write # push image + manifests OCI artifact
      id-token: write # keyless cosign signing
    uses: devantler-tech/reusable-workflows/.github/workflows/publish-app.yaml@59c9a1792fbef2d5849127a1c892ed39990645d9 # v5.5.5
    with:
      app-name: wedding-app
