name: 🎉 Release
on:
  push:
    branches: [main]
  workflow_dispatch: 

permissions: {}

jobs:
  release:
    uses: devantler-tech/actions/.github/workflows/create-release.yaml@5aa2657f976103d716f585266a0fa4e964594df2 # v9.0.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
